### ISSUE TITLE
Column names order

### ISSUE THREAD

**Issue by ghost** [z5h/json.pivot#2]
Don't know if you are still maintaining this. anyhow...

After calling `pivot(data, rows, columns, {})` the column names are not ordered as passed in the data. 

Example:

```
data = [{ brand: 1, month: 1, value: 150 }, { brand: 1, month: 2, value: 150 }, ..., { brand: 1, month: 10, value: 150 }]
```

I passed the month as column but then, instead of the columns showing `1  |   2   |   3 |` it was ordering alphabetically `1   |   10   |   11   |   12   |   2   |`

Thanks in advanced.

**Comment by z5h** [comment]
Comparators for sorting are created based on the data. 
See here: https://github.com/z5h/json.pivot/blob/master/src/jp.js#L148

Is it possible of the the month values is null or a String value?
If that's  not the case, can you provide some exact code that illustrates the problem?

Thanks.

**Comment by ghost** [comment]
You are very right. The months are in a string format.
